### ISSUE TITLE
Authsign signatures very slow

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/integrity-backend#101]
Authsign signatures takes 2 mins to complete

Traced to this code in `integritybackend/file_util.py`` file def `authsign_sign`

```
        r = requests.post(
            authsign_server_url + "/sign",
            headers=headers,
            json={"hash": data_hash, "created": dt},
        )
```

- [x] Check speed of authsign direct - speed fast
- [x] Check speed from integrity server - curl speed fast
- [x] Check speed from pythong isolated code curl speed fast 2 mins
- [ ] Deploy ipv6 firewall on all servers

**Comment by YurkoWasHere** [comment]
both localhost and proxied url sign and verifies under 1 second using exact same code

```
    r = requests.post(
        _AUTHSIGN_URL + "/sign",
        headers={"Authorization": f"bearer {_AUTHSIGN_TOKEN}"},
        json={"hash": data_hash, "created": dt},
    )
    #print(r.text)
    r.raise_for_status()
```

**Comment by YurkoWasHere** [comment]
```
time curl -X POST https://<URL>/sign  -H 'Content-Type: application/json' -H 'Authorization: bearer <authtoken>' -d '{"hash": "test-hash", "created": "2022-05-16T12:42:37Z"}'
```
real    0m0.389s
user    0m0.008s
sys     0m0.000s

while
```

vs
```
    print ("START " + str(datetime.utcnow()))
    r = requests.post(
        _AUTHSIGN_URL + "/sign",
        headers={"Authorization": f"bearer {_AUTHSIGN_TOKEN}"},
        json={"hash": data_hash, "created": dt},
    )
    print ("END " + str(datetime.utcnow()))
```
START 2022-05-16 12:48:37.801079
END 2022-05-16 12:50:47.534088

**Comment by YurkoWasHere** [comment]
adding timout=5 seems to mitigate the problem
```
    r = requests.post(
        _AUTHSIGN_URL + "/sign",
        headers={"Authorization": f"bearer {_AUTHSIGN_TOKEN}"},
        json={"hash": data_hash, "created": dt},timeout=5
    )
```

Suggestion is that this indicates a problem with IPV6 and timeout fails over to IPV4 but  CURL works on both ipv6 and 4 quickly.

**Comment by YurkoWasHere** [comment]
IPv6 firewall was DROP ALL. Updated ansible script to enable ipv6

**Comment by benhylau** [comment]
Is this still relevant?

**Comment by YurkoWasHere** [comment]
Patch already done.. Closing issue
