### ISSUE TITLE
Document all server configs

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#122]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Document **all** server config keys in README.  

The README currently only documents only a subset of the server configs, and the selection is kind of arbitrary. For example, `C2PATOOL_PATH` is documented but `IPFS_CLIENT_PATH` isn't. It is also unclear what is required vs. optional, and when is something needed.

There are names that don't tell very much what they are (e.g. `JWT_SECRET` and `KEY_STORE`). This is especially confusing since we added features like `C2PA_CERT_STORE`. How is this functionally different from `KEY_STORE`?

So this ticket is to add documenting to all the keys in `.env`, without changing the config names themselves.

## To Do

- [x] sort keys in `.env` and example file
- [x] update README with explanation of each key in https://github.com/starlinglab/integrity-backend#configuration
  - be clear when a key is needed
  - which is optional vs. required, and when

**Comment by makeworld-the-better-one** [comment]
Completed in #131
