### ISSUE TITLE
Implement archiving Action

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#67]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Implement components that generates and registers encrypted archiving according to archiving policy on a collection.  

Draft workflow:

<img width="902" alt="Screen Shot 2022-03-10 at 10 40 34 AM" src="https://user-images.githubusercontent.com/2261308/157698021-ecd5e1b9-da1c-4cbc-bf7a-ba14b968ad76.png">

## To Do

- [ ] ...

**Comment by anaulin** [comment]
In today's discussion with @makeworld-the-better-one and @benhylau we determined that, for now, we can push the task of batching to the different data producers (i.e. each bot, web archivers, etc). That way each data producer can implement the batching logic that makes most sense for their particular type of data.

In the mid/long-term, we can build a separate "batching service" (which could be a cronjob or a filesystem watcher or an HTTP API) that could ingest data for a collection and make smart decisions about when there is enough to be "batched up". But that's for later.

For now, we will focus on the "archive" functionality, which will watch a folder for files to archive.

**Comment by benhylau** [comment]
@makeworld-the-better-one from today's discussion:

1. Copy ZIP file to a temporary directory for processing (i.e. unzip, append to zip, etc.)
2. Verify asset file, reject otherwise:
    - name matches `sha256(asset)`
    - extension is contained in `asset_extensions` for Collection
3. Generate [ CIDv1, SHA256, MD5 ] hashes for the asset file
4. Register on opentimestamp and download proof file into `$ZIP_ROOT/proofs/`
5. Take final archive ZIP:
    - generate [ CIDv1, SHA256, MD5 ] hashes
    - store as `./internal/organization_id/collection_id/action-archive/sha256(hash).zip`
5. Encrypt final archive ZIP with `encryption` params, take the encrypted output:
    - generate [ CIDv1, SHA256, MD5 ] hashes
    - store as `./internal/organization_id/collection_id/action-archive/sha256(hash).encrypted`
6. (TBD) Generate registration record JSON for Numbers Protocol:
    - generate JSON with `numbersprotocol` params
    - sign JSON with `authsigner` params
    - store as `./internal/organization_id/collection_id/action-archive/sha256(hash)-numbersprotocol-record.json`
    - register with Numbers Protocol module
6. (TBD) Generate registration record JSON for ISCN:
    - generate JSON with `iscn` params
    - sign JSON with `authsigner` params
    - store as `./internal/organization_id/collection_id/action-archive/sha256(hash)-iscn-record.json`
    - register with Numbers Protocol module

**Comment by makeworld-the-better-one** [comment]
- Incoming ZIP file must be named to the SHA-256 hash of the ZIP, and rejected otherwise
- Incoming ZIPs are dropped into the folder `input` under the collection ID
- Copying the ZIP from `input` from `action-archive` happens at the beginning, and is done by the `archive` func

**Comment by makeworld-the-better-one** [comment]
#76 has been merged to `dev` but is not yet complete, as it does not implement steps 7 and 8.

**Comment by benhylau** [comment]
This is implemented. Refactoring of this is tracked under https://github.com/starlinglab/integrity-backend/issues/114
