### ISSUE TITLE
C2PA on proofmode JPGs

### ISSUE THREAD

**Issue by makeworld-the-better-one** [starlinglab/integrity-backend#93]
## Task Summary

📅 **Due date:** Monday May 2  
🎯 **Success criteria:** Working `c2pa_proofmode` action

* Get rid of `create_proofmode` func
* Func: c2pa-proofmode / c2pa_proofmode 
	- Input: zip path, config JSON
	- Unzip
	- Read from content_metadata to get photographer name (use Signal number for now): ``"private": { "signal": { "source": "+16475551234",`` 
	- Take each jpeg and inject
	- Output folder in shared FS: `<org_id>/<collection_id>/c2pa_proofmode_output/<photographer_name>/<date "YYYY-MM-DD">`

**Comment by makeworld-the-better-one** [comment]
What timezone should the dates been in? For now I'll use UTC.

**Comment by makeworld-the-better-one** [comment]
Draft PR made: https://github.com/starlinglab/integrity-backend/pull/94

@benhylau not sure what you want in the claim JSON/dictionary so I haven't filled out the code for that.

**Comment by benhylau** [comment]
Updated PR. Pls review :)

**Comment by makeworld-the-better-one** [comment]
New PR for this issue: #95

**Comment by benhylau** [comment]
Done
