### ISSUE TITLE
Verification of ProofMode signatures

### ISSUE THREAD

**Issue by makeworld-the-better-one** [starlinglab/integrity-backend#96]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Verify file signatures from ProofMode applications

- Related: #89
- Not urgent
- Verifies signatures in proofmode zip, **in the preprocessor**
- Current proofmode preprocessor code is happening [here](https://github.com/starlinglab/integrity-preprocessor/blob/dev/common/common.py#L39), at `parse_proofmode_data`

## To Do

- [ ] ...

**Comment by makeworld-the-better-one** [comment]
Proofmode uses OpenPGP for signatures, so basically only gpg or a gpg wrapper can be used from Python to verify it. Here is some code that shells out to gpg and can verify ProofMode signatures.

```python3
def dearmor_gpg_key(key, out):
    """
    Write dearmored version of a PEM-encoded gpg key.

    All arguments are paths.
    """

    subprocess.run(["gpg", "-o", out, "--dearmor", key], check=True)


def verify_gpg_sig(key, sig, msg):
    """
    Verify if gpg signature is correct

    All arguments are paths. The key path should be absolute.
    The key path has to be to a dearmored key, not a original key from ProofMode.

    True is returned if the signature verified, False if not.
    """

    proc = subprocess.run(
        ["gpg", "--no-default-keyring", "--keyring", key, "--verify", sig, msg],
        stderr=subprocess.DEVNULL,
    )
    if proc.returncode == 0:
        return True
    if proc.returncode == 1:
        return False
    # Some other unexpected return code, means an error has occured
    proc.check_returncode()
```

I'm working on integrating this into the preprocessor on my own branch, but it's low priority. I put it here in case @YurkoWasHere wants to jump ahead and use it. Let me know if you do.

**Comment by YurkoWasHere** [comment]
pgpy seems to not require gpg binary

Don't know if you looked at this, or if it would be valuable vs shell gpg

https://pgpy.readthedocs.io/en/latest/examples.html

**Comment by makeworld-the-better-one** [comment]
Nice find! Looks like it would work for this use case. The advantage is that it wouldn't require a gpg binary to be installed, but the disadvantages are that's it's more likely to have bugs, and having to manage another Python dependency. It seems like shelling out might be better, but I can switch to pgpy if you think that makes more sense.

**Comment by YurkoWasHere** [comment]
Yes it was a "hidden gem". 

I think it makes sense to stick to binary for now. I will have to add this dependency in the ansible scripts.

Can you suggest a Debian package to use (gnupg or gnupg2 or other?)

**Comment by makeworld-the-better-one** [comment]
Install `gnupg`, that should be all we need. The `gpg` package doesn't have all the tools and so I want to avoid it just in case, and `gnupg2` is just a "dummy transitional package" that adds some symlinks.

**Comment by YurkoWasHere** [comment]
✅Done

https://github.com/starlinglab/integrity-deploy/commit/dd01cc8c3cdb48585efa7649f14e7df1e0e86dc2

**Comment by makeworld-the-better-one** [comment]
PR was merged. As per #103, it will need to be moved from where it is in the preprocessor code into a verify module.
